mission_control:
  fly_height: 0.7
  fly_height_ball: 1.03
  fly_height_drop: 0.5
  delta: 0.07

  point1_x: 2.93
  point1_y: 0.0

  point2_x: 3.14
  point2_y: 1.64
  
  point3_x: 0.0
  point3_y: 1.22

  point4_x: 0.03
  point4_y: 3.94

  point5_x: 0.0
  point5_y: 2.5

  point6_x: 1.4
  point6_y: 2.6

  point7_x: 2.9
  point7_y: 2.5

  point8_x: 4.4
  point8_y: 2.3

  # 红
  land_point_r_x: 4.0
  land_point_r_y: 0.5
  # 绿
  land_point_g_x: 4.5
  land_point_g_y: 1.5
  # 蓝
  land_point_b_x: 5.0
  land_point_b_y: 0.5

  # y+0.5
  drop_point_r_x: 4.0
  drop_point_r_y: 0.0

  drop_point_g_x: 4.5
  drop_point_g_y: 1.0

  drop_point_b_x: 5.0
  drop_point_b_y: 0.0



  #识别区
  recog_x: 0.045
  recog_y: 3.4